// loot drops
// potions
const manaOrb = {
	radius: 20,
	name: "manaOrb",
	spellBookName: null,
	rarity: "uncommon",
	dropChance: 25,
	appearance: "lootDrop/manaOrb.png",
	form: "effect",
	type: "others",
	essenceName: null,
	pagesToCraft: null,
	essenceToCraft: null,
	ignoreCollision: false,
	quantity: 1,
	stackLimit: 9999,
	text: "spike"
};
// folklore essence
const glowEssence = {
	radius: 20,
	name: "glowEssence",
	spellBookName: null,
	rarity: "common",
	dropChance: 100,
	appearance: "lootDrop/glowEssence.png",
	form: "essence",
	type: "glow",
	essenceName: null,
	pagesToCraft: null,
	essenceToCraft: null,
	ignoreCollision: false,
	quantity: 1,
	stackLimit: 9999,
	text: "Glow Essence"
};
const gloomEssence = {
	radius: 20,
	name: "gloomEssence",
	spellBookName: null,
	rarity: "common",
	dropChance: 100,
	appearance: "lootDrop/gloomEssence.png",
	form: "essence",
	type: "gloom",
	essenceName: null,
	pagesToCraft: null,
	essenceToCraft: null,
	ignoreCollision: false,
	quantity: 1,
	stackLimit: 9999,
	text: "Gloom Essence"
};
// folklore Pages
const spikePage = {
	radius: 20,
	name: "spikePage",
	spellBookName: spellBookLibrary.spikeBook,
	rarity: "uncommon",
	dropChance: 250,
	appearance: "lootDrop/spike_page.png",
	form: "page",
	type: "gloom",
	essenceName: "gloomEssence",
	pagesToCraft: 5,
	essenceToCraft: 15,
	ignoreCollision: false,
	quantity: 1,
	stackLimit: 9999,
	text: "spike"
};
const luminousEnergyPage = {
	radius: 20,
	name: "luminousEnergyPage",
	spellBookName: spellBookLibrary.luminousEnergyBook,
	rarity: "uncommon",
	dropChance: 25,
	appearance: "lootDrop/luminousEnergy_page.png",
	form: "page",
	type: "glow",
	essenceName: "glowEssence",
	pagesToCraft: 5,
	essenceToCraft: 15,
	ignoreCollision: false,
	quantity: 1,
	stackLimit: 9999,
	text: "lumenergy"
};
const glowShardPage = {
	radius: 20,
	name: "glowShardPage",
	spellBookName: spellBookLibrary.glowShardBook,
	rarity: "uncommon",
	dropChance: 25,
	appearance: "lootDrop/glowShard_page.png",
	form: "page",
	type: "glow",
	essenceName: "glowEssence",
	pagesToCraft: 5,
	essenceToCraft: 15,
	ignoreCollision: false,
	quantity: 1,
	stackLimit: 9999,
	text: "glow shard"
};
const luminousShieldPage = {
	radius: 20,
	name: "luminousShieldPage",
	spellBookName: spellBookLibrary.luminousShieldBook,
	rarity: "uncommon",
	dropChance: 25,
	appearance: "lootDrop/luminousShield_page.png",
	form: "page",
	type: "glow",
	essenceName: "glowEssence",
	pagesToCraft: 5,
	essenceToCraft: 15,
	ignoreCollision: false,
	quantity: 1,
	stackLimit: 9999,
	text: "lumshield"
};
const luminousSpiritPage = {
	radius: 20,
	name: "luminousSpiritPage",
	spellBookName: spellBookLibrary.luminousSpiritBook,
	rarity: "uncommon",
	dropChance: 25,
	appearance: "lootDrop/luminousSpirit_page.png",
	form: "page",
	type: "glow",
	essenceName: "glowEssence",
	pagesToCraft: 5,
	essenceToCraft: 15,
	ignoreCollision: false,
	quantity: 1,
	stackLimit: 9999,
	text: "spirit"
};
const specterPage = {
	radius: 20,
	name: "specterPage",
	spellBookName: spellBookLibrary.specterBook,
	rarity: "uncommon",
	dropChance: 25,
	appearance: "lootDrop/specter_page.png",
	form: "page",
	type: "gloom",
	essenceName: "gloomEssence",
	pagesToCraft: 5,
	essenceToCraft: 15,
	ignoreCollision: false,
	quantity: 1,
	stackLimit: 9999,
	text: "specter"
};
const specterHandPage = {
	radius: 20,
	name: "specterHandPage",
	spellBookName: spellBookLibrary.specterHandBook,
	rarity: "uncommon",
	dropChance: 25,
	appearance: "lootDrop/specterHand_page.png",
	form: "page",
	type: "gloom",
	essenceName: "gloomEssence",
	pagesToCraft: 5,
	essenceToCraft: 15,
	ignoreCollision: false,
	quantity: 1,
	stackLimit: 9999,
	text: "hand"
};
const teleportPage = {
	radius: 20,
	name: "teleportPage",
	spellBookName: spellBookLibrary.castTeleportBook,
	rarity: "uncommon",
	dropChance: 25,
	appearance: "lootDrop/teleport_page.png",
	form: "page",
	type: "glow",
	essenceName: "glowEssence",
	pagesToCraft: 5,
	essenceToCraft: 15,
	ignoreCollision: false,
	quantity: 1,
	stackLimit: 9999,
	text: "teleport"
};
const smashPage = {
	radius: 20,
	name: "smashPage",
	spellBookName: spellBookLibrary.castSmashBook,
	rarity: "uncommon",
	dropChance: 25,
	appearance: "lootDrop/smash_page.png",
	form: "page",
	type: "fire",
	essenceName: "fireEssence",
	pagesToCraft: 5,
	essenceToCraft: 15,
	ignoreCollision: false,
	quantity: 1,
	stackLimit: 9999,
	text: "smash"
};
const beamPage = {
	radius: 20,
	name: "beamPage",
	spellBookName: spellBookLibrary.beamBook,
	rarity: "uncommon",
	dropChance: 25,
	appearance: "lootDrop/beam_page.png",
	form: "page",
	type: "glow",
	essenceName: "glowEssence",
	pagesToCraft: 5,
	essenceToCraft: 15,
	ignoreCollision: false,
	quantity: 1,
	stackLimit: 9999,
	text: "beam"
};
const lightningBoltPage = {
	radius: 20,
	name: "lightningBoltPage",
	spellBookName: spellBookLibrary.lightningBoltBook,
	rarity: "uncommon",
	dropChance: 25,
	appearance: "lootDrop/lightningBolt_page.png",
	form: "page",
	type: "glow",
	essenceName: "glowEssence",
	pagesToCraft: 5,
	essenceToCraft: 15,
	ignoreCollision: false,
	quantity: 1,
	stackLimit: 9999,
	text: "lightning"
};
const energyBallPage = {
	radius: 20,
	name: "energyBallPage",
	spellBookName: spellBookLibrary.energyBallBook,
	rarity: "uncommon",
	dropChance: 25,
	appearance: "lootDrop/energyBall_page.png",
	form: "page",
	type: "glow",
	essenceName: "glowEssence",
	pagesToCraft: 5,
	essenceToCraft: 15,
	ignoreCollision: false,
	quantity: 1,
	stackLimit: 9999,
	text: "energy ball"
};
const treePage = {
	radius: 20,
	name: "treePage",
	spellBookName: spellBookLibrary.treeBook,
	rarity: "rare",
	dropChance: 10,
	appearance: "lootDrop/summonTree_page.png",
	form: "page",
	type: "gloom",
	essenceName: "gloomEssence",
	pagesToCraft: 5,
	essenceToCraft: 15,
	ignoreCollision: false,
	quantity: 1,
	stackLimit: 9999,
	text: "tree"
};